spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/TravelLog
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
      hibernate:
        ddl-auto: create
  sql:
    init:
      mode: always
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  session:
    timeout: 86400
    jdbc:
      initialize-schema: always

travellog:
  jwt-key : "jit2KkRsOzIk9gqBiH1siP8uvcSg4E1khxXHl8bnakA="

